sudo: required

services:
  - docker

language: python

python:
 - "2.7"

before_install:
  - docker-compose --version
  - docker --version
  - docker-compose -f tests/integration/docker-compose.yml up -d

install: pip install -r requirements.txt

script:
  - nosetests tests/unit/
  - tests/integration/run_tests.sh

